package com.kgl.glfw

import org.lwjgl.glfw.GLFW.*

actual enum class GamepadButton(internal val value: Int) {
	A(GLFW_GAMEPAD_BUTTON_A),
	B(GLFW_GAMEPAD_BUTTON_B),
	X(GLFW_GAMEPAD_BUTTON_X),
	Y(GLFW_GAMEPAD_BUTTON_Y),
	LEFT_BUMPER(GLFW_GAMEPAD_BUTTON_LEFT_BUMPER),
	RIGHT_BUMPER(GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER),
	BACK(GLFW_GAMEPAD_BUTTON_BACK),
	START(GLFW_GAMEPAD_BUTTON_START),
	GUIDE(GLFW_GAMEPAD_BUTTON_GUIDE),
	LEFT_THUMB(GLFW_GAMEPAD_BUTTON_LEFT_THUMB),
	RIGHT_THUMB(GLFW_GAMEPAD_BUTTON_RIGHT_THUMB),
	DPAD_UP(GLFW_GAMEPAD_BUTTON_DPAD_UP),
	DPAD_RIGHT(GLFW_GAMEPAD_BUTTON_DPAD_RIGHT),
	DPAD_DOWN(GLFW_GAMEPAD_BUTTON_DPAD_DOWN),
	DPAD_LEFT(GLFW_GAMEPAD_BUTTON_DPAD_LEFT);

	actual companion object {
		internal fun from(value: Int) = values()[value - GLFW_GAMEPAD_BUTTON_A]
	}
}
