/**
 * Copyright [2019] [Dominic Fischer]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.kgl.vulkan.enums

import com.kgl.vulkan.utils.VkFlag
import org.lwjgl.vulkan.EXTSamplerFilterMinmax
import org.lwjgl.vulkan.IMGFilterCubic
import org.lwjgl.vulkan.VK11

actual enum class FormatFeature(override val value: Int) : VkFlag<FormatFeature> {
	SAMPLED_IMAGE(VK11.VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT),

	STORAGE_IMAGE(VK11.VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT),

	STORAGE_IMAGE_ATOMIC(VK11.VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT),

	UNIFORM_TEXEL_BUFFER(VK11.VK_FORMAT_FEATURE_UNIFORM_TEXEL_BUFFER_BIT),

	STORAGE_TEXEL_BUFFER(VK11.VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_BIT),

	STORAGE_TEXEL_BUFFER_ATOMIC(VK11.VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_ATOMIC_BIT),

	VERTEX_BUFFER(VK11.VK_FORMAT_FEATURE_VERTEX_BUFFER_BIT),

	COLOR_ATTACHMENT(VK11.VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT),

	COLOR_ATTACHMENT_BLEND(VK11.VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT),

	DEPTH_STENCIL_ATTACHMENT(VK11.VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT),

	BLIT_SRC(VK11.VK_FORMAT_FEATURE_BLIT_SRC_BIT),

	BLIT_DST(VK11.VK_FORMAT_FEATURE_BLIT_DST_BIT),

	SAMPLED_IMAGE_FILTER_LINEAR(VK11.VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT),

	SAMPLED_IMAGE_FILTER_CUBIC_IMG(IMGFilterCubic.VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_CUBIC_BIT_IMG),

	TRANSFER_SRC(VK11.VK_FORMAT_FEATURE_TRANSFER_SRC_BIT),

	TRANSFER_DST(VK11.VK_FORMAT_FEATURE_TRANSFER_DST_BIT),

	SAMPLED_IMAGE_FILTER_MINMAX_EXT(EXTSamplerFilterMinmax.VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_MINMAX_BIT_EXT),

	MIDPOINT_CHROMA_SAMPLES(VK11.VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT),

	SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER(VK11.VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT),

	SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER(VK11.VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT),

	SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT(VK11.VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT),

	SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE(VK11.VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT),

	DISJOINT(VK11.VK_FORMAT_FEATURE_DISJOINT_BIT),

	COSITED_CHROMA_SAMPLES(VK11.VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT);

	companion object {
		private val enumLookUpMap: Map<Int, FormatFeature> =
				enumValues<FormatFeature>().associateBy({ it.value })

		fun fromMultiple(value: Int): VkFlag<FormatFeature> = VkFlag(value)

		fun from(value: Int): FormatFeature = enumLookUpMap[value]!!
	}
}

